target-version = "py312"

line-length = 100

indent-width = 4

src = ["app", "tests"]

exclude = [
    ".venv",
    "__pycache__",
    "logs",
    "data"
]

[lint]

select = [
    "E",
    "F",
    "I",
    "UP",
    "B"
]

ignore = [
]